# Generated by Django 2.1.1 on 2018-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='skype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='social',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
