# Generated by Django 2.1.1 on 2018-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181028_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
    ]
