# Generated by Django 2.1.1 on 2018-11-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('f', 'Формируется'), ('w', 'Работает'), ('s', 'Приостановлена'), ('e', 'Завершена')], max_length=1)),
                ('level', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subject')),
            ],
        ),
    ]
