# Generated by Django 2.1.1 on 2018-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teachers',
            field=models.ManyToManyField(related_name='schedules', to='app.Member'),
        ),
    ]
