# Generated by Django 2.2 on 2019-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181121_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duty', models.CharField(blank=True, max_length=250)),
                ('salary', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
